import uuid

from fastapi import APIRouter, Depends, Header, HTTPException, Response
from pydantic import ValidationError
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.auth.dependencies import get_current_active_user
from app.models.connection import get_db
from app.models.database import Deduction, IncomeSource, TaxProfile, User
from app.models.schemas import (
    ChatProfileUpdateApply,
    DeductionCreate,
    DeductionUpdate,
    IncomeSourceCreate,
    IncomeSourceUpdate,
    TaxProfileCreate,
    TaxProfileRead,
    TaxProfileUpdate,
)
from app.services.profile_version import bump_profile_version, lock_profile_version

router = APIRouter(prefix="/tax-profiles", tags=["tax_profiles"])

# Fields the in-chat "update your profile?" card is allowed to write, by entity.
_PROFILE_SCALAR_FIELDS = {
    "marital_status",
    "filing_status",
    "residency_status",
    "num_dependents",
    "claims_dependents_exemption",
    "claim_spouse_expense_exemption",
    "disability_exemption_count",
}
_INCOME_FIELDS = {"amount", "tax_withheld", "employer_name", "type"}


def _validated_field(schema: type, field: str, value: object) -> object:
    """Apply the same bounds and enum validation as the regular edit routes."""
    if value is None and field != "employer_name":
        raise HTTPException(status_code=422, detail=f"{field} cannot be null")
    try:
        parsed = schema.model_validate({field: value})
    except ValidationError as exc:
        raise HTTPException(status_code=422, detail=str(exc)) from exc
    return getattr(parsed, field)


def _validated_payload(schema: type, payload: dict) -> object:
    try:
        return schema.model_validate(payload)
    except ValidationError as exc:
        raise HTTPException(status_code=422, detail=str(exc)) from exc


@router.post("/", response_model=TaxProfileRead, status_code=201)
async def create_tax_profile(
    data: TaxProfileCreate,
    current_user: User = Depends(get_current_active_user),
    db: AsyncSession = Depends(get_db),
):
    payload = data.model_dump(exclude={"user_id"})
    if "claims_dependents_exemption" not in data.model_fields_set:
        payload["claims_dependents_exemption"] = (
            data.marital_status == "married" or data.num_dependents > 0
        )
    if "claim_spouse_expense_exemption" not in data.model_fields_set:
        payload["claim_spouse_expense_exemption"] = data.marital_status == "married"
    profile = TaxProfile(**payload, user_id=current_user.id)
    db.add(profile)
    await db.commit()
    await db.refresh(profile)
    return profile


@router.get("/", response_model=list[TaxProfileRead])
async def list_tax_profiles(
    current_user: User = Depends(get_current_active_user),
    db: AsyncSession = Depends(get_db),
):
    stmt = select(TaxProfile).where(TaxProfile.user_id == current_user.id)
    result = await db.execute(stmt)
    return result.scalars().all()


@router.get("/{profile_id}", response_model=TaxProfileRead)
async def get_tax_profile(
    profile_id: uuid.UUID,
    current_user: User = Depends(get_current_active_user),
    db: AsyncSession = Depends(get_db),
):
    profile = await db.get(TaxProfile, profile_id)
    if not profile or profile.user_id != current_user.id:
        raise HTTPException(status_code=404, detail="Tax profile not found")
    return profile


@router.put("/{profile_id}", response_model=TaxProfileRead)
async def update_tax_profile(
    profile_id: uuid.UUID,
    data: TaxProfileUpdate,
    current_user: User = Depends(get_current_active_user),
    db: AsyncSession = Depends(get_db),
    if_match: int | None = Header(None, alias="If-Match"),
):
    profile = await db.get(TaxProfile, profile_id)
    if not profile or profile.user_id != current_user.id:
        raise HTTPException(status_code=404, detail="Tax profile not found")
    await lock_profile_version(db, profile_id, if_match)
    for field, value in data.model_dump(exclude_unset=True).items():
        setattr(profile, field, value)
    if data.model_fields_set:
        await bump_profile_version(db, profile_id)
    await db.commit()
    await db.refresh(profile)
    return profile


@router.post("/{profile_id}/apply-chat-update", response_model=TaxProfileRead)
async def apply_chat_update(
    profile_id: uuid.UUID,
    data: ChatProfileUpdateApply,
    current_user: User = Depends(get_current_active_user),
    db: AsyncSession = Depends(get_db),
    if_match: int | None = Header(None, alias="If-Match"),
):
    """Apply a confirmed in-chat profile-update suggestion to the stored account.

    Validates entity + field against an allowlist and routes the write to the right
    table, all scoped to the signed-in user. The suggestion itself is generated by
    the chat understanding layer (see rag/account_context.build_profile_updates).
    """
    profile = await db.get(TaxProfile, profile_id)
    if not profile or profile.user_id != current_user.id:
        raise HTTPException(status_code=404, detail="Tax profile not found")
    await lock_profile_version(db, profile_id, if_match)

    if data.action not in {"update", "create"}:
        raise HTTPException(status_code=422, detail="action must be 'update' or 'create'")

    if data.entity == "tax_profile":
        if data.action != "update" or data.field not in _PROFILE_SCALAR_FIELDS:
            raise HTTPException(status_code=422, detail=f"Cannot apply {data.field!r} to the profile")
        setattr(profile, data.field, _validated_field(TaxProfileUpdate, data.field, data.new_value))

    elif data.entity == "income_source":
        if data.field not in _INCOME_FIELDS:
            raise HTTPException(status_code=422, detail=f"Cannot apply {data.field!r} to income")
        if data.action == "create":
            if data.field != "amount":
                raise HTTPException(status_code=422, detail="Only income amount can create a source")
            amount = _validated_field(IncomeSourceUpdate, "amount", data.new_value)
            validated = _validated_payload(IncomeSourceCreate,
                {"tax_profile_id": profile.id, "type": "salary", "amount": amount}
            )
            row = IncomeSource(
                tax_profile_id=profile.id,
                type=validated.type,
                amount=validated.amount,
            )
            db.add(row)
        else:
            if data.entity_id is None:
                raise HTTPException(status_code=422, detail="entity_id required for update")
            row = await db.get(IncomeSource, data.entity_id)
            if not row or row.tax_profile_id != profile.id:
                raise HTTPException(status_code=404, detail="Income source not found")
            setattr(row, data.field, _validated_field(IncomeSourceUpdate, data.field, data.new_value))

    elif data.entity == "deduction":
        if data.field != "amount":
            raise HTTPException(status_code=422, detail="Only deduction amount is updatable here")
        if data.action == "create":
            if not data.category:
                raise HTTPException(status_code=422, detail="category required to create a deduction")
            amount = _validated_field(DeductionUpdate, "amount", data.new_value)
            validated = _validated_payload(DeductionCreate,
                {"tax_profile_id": profile.id, "category": data.category, "amount": amount}
            )
            db.add(
                Deduction(
                    tax_profile_id=profile.id,
                    category=validated.category,
                    amount=validated.amount,
                )
            )
        else:
            if data.entity_id is None:
                raise HTTPException(status_code=422, detail="entity_id required for update")
            row = await db.get(Deduction, data.entity_id)
            if not row or row.tax_profile_id != profile.id:
                raise HTTPException(status_code=404, detail="Deduction not found")
            row.amount = _validated_field(DeductionUpdate, "amount", data.new_value)

    else:
        raise HTTPException(status_code=422, detail=f"Unknown entity {data.entity!r}")

    await bump_profile_version(db, profile_id)
    await db.commit()
    await db.refresh(profile)
    return profile


@router.delete("/{profile_id}", status_code=204)
async def delete_tax_profile(
    profile_id: uuid.UUID,
    current_user: User = Depends(get_current_active_user),
    db: AsyncSession = Depends(get_db),
):
    profile = await db.get(TaxProfile, profile_id)
    if not profile or profile.user_id != current_user.id:
        raise HTTPException(status_code=404, detail="Tax profile not found")
    await db.delete(profile)
    await db.commit()
    return Response(status_code=204)
